/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}, ],

  // But you can create a sidebar manually


 /* faqSideBar:[{type: 'doc',   id: 'cat-FAQs',   label: 'FAQs'}],*/
  
  /*bcSidebar:[    
    {
    type: 'category',
    label: 'Beacon Chain',
   // collapsible: true,
    collapsed: true,
    items: ['bcdevelop'],//'develop','Learn','Validate','Integrate','Wallet', 'FAQs'],
     /* {
        type: 'category',
        collapsible: true,
        collapsed: false,
        label: 'Develop',
        items: ['develop'], //add the names of the docs as per the list to create
      },
      'Learn','Validate','Integrate','Wallet', 'FAQs'],
      },
     ],
*/
/*  beaconSideBar :[
    {
      type: 'category',
      label: 'Beacon Chain',
     // collapsible: true,
      collapsed: true,
      items: ['beacon-intro' ],
    },
  ],*/

  bscSideBar: [
    {
      type: 'category',
      label: 'Build N\' Build',
     // collapsible: true,
      collapsed: true,
      items: ['bnbIntro', 'getting-started'],
    },

    {
      type: 'category',
      collapsible: true,
      collapsed: true,
      label: 'BNB Smart Chain',
      items: ['learn/intro',
        //{type: 'category', collapsed:true,  label: 'About',   items: ['learn/intro', 'learn/terminology']},
          {
          type: 'category',
          //collapsible: true,
          collapsed: true,
          label: 'Core Concepts',
          items: ['learn/consensus', //'learn/genesis',
                    {type: 'category',
                    //collapsible: true,
                    collapsed: true,
                    label: 'BC and BSC Cross-Chain Mechanism',
                    items: ['learn/cross-chain', 'learn/system-contract',
                            'learn/cross-chain-transfer','learn/bsc-relayer', 'learn/incentives',
                            'learn/oracle-module','learn/oracle-relayer']},
                            //'learn/bsc-gov-workflow',
                            'learn/bsc-gov']
          },
          {
            type: 'doc', label: 'Tools', id:'learn/ecosystem'
          },

        {type: 'category',
        //collapsible: true,
        collapsed: true,
        label: 'Develop',
        items: ['BSCmainnet', 'BSCtestnet', 'BSCexplorers',
                {
                  type: 'category',
                            //collapsible: true,
                            collapsed: true,
                            label: 'Running Fullnode',
                            items: ['validator/fullnode','validator/snapshot','local', 'validator/upgrade-fullnode']
                },
                {type:'doc', id:'rpc', label:'RPC'},
                {
                  type: 'category',
                  //collapsible: true,
                  collapsed: true,
                  label: 'Deploy Smart Contract',
                  items: ['remix', 'truffle', 'hardhat', 'verify']
                },
                {
                  type: 'category',
                  collapsed: true,
                  label: 'Deploy NFTs',
                  items:['nft-metadata-standard', 'ERC721']},
                {
                  type: 'category',
                  //collapsible: true,
                  collapsed: true,
                  label: 'BEP20 Contracts',
                  items: ['proxy', 'verify-proxy']
                },
                {
                  type: 'category',
                  //collapsible: true,
                  collapsed: true,
                  label: 'BEP20 Tokens',
                  items: ['BEP20', 'issue-BEP20',
                            {
                              type: 'category',
                              //collapsible: true,
                              collapsed: true,
                              label: 'Bind Tokens',
                              items: ['tokens-cross-chain', 'bind-tokens', 'mirror', 
                              'circulation-model', 'sync' ]
                            },
                            'cross-chain-transfer'
                         ]
                }, 
                
                 'bsc-relayer', //'cross-chain-tech',
                {
                  type: 'category',
                  //collapsible: true,
                  collapsed: true,
                  label: 'Oracles',
                  items: ['band',  'link']
                },
                {type: 'doc', id: 'learn/cross-chain-app-list', label: 'Cross-Chain App Support'},
       ]},  
       
       {
        type: 'category',
        //collapsible: true,
        collapsed: true,
        label: 'Validator',
        items: ['validator/overview', 'validator/requirements', 
                {
                  type: 'category',
                  //collapsible: true,
                  collapsed: true,
                  label: 'Running as Validator on BSC',
                  items:['validator/guideline-mainnet',
                  {
                    type: 'category',
                  collapsed: true,
                  label: 'Join Testnet',
                  items:['validator/guideline-testnet', 'validator/testnet']
                  },
                   
                   'validator/snapshot', ]
                },
                //'validator/security', 
                'validator/best-practice','validator/node-maintenance',
                'validator/commonproblems', 'validator/troubleshoot'], 
       },
       {
        type: 'category',
        //collapsible: true,
        collapsed: true,
        label: 'Staking',
        items: ['stake/Staking', 'stake/cli-commands',
        {
          type: 'category',
          collapsed: true,
          label: 'Slashing',
          items:['validator/Penalty-overview', 'validator/send-slash-evidence', 
                 'validator/scenarios-slash', 'validator/slash-fee', 'validator/unjail',
                 'validator/monitor-and-query-slash'
          ]
        },
        'del-guide']
      },
      /*{type:'doc', id:'Staking', label:'Staking on BSC'},*/
      //{type: 'doc',   id: 'del-guide',   label: 'Delegator Guide'},
  
      {type: 'doc',   id: 'Integrate',   label: 'Integration'},

      {
        type: 'category',
        //collapsible: true,
        collapsed: true,
        label: 'Wallet',
        items: ['Wallet', 'create-wallet', 
        {
          type: 'category',
          //collapsible: true,
          collapsed: true,
          label: 'Beacon Extension Wallet',
          items: ['binance','manual', 'add-account', 'wallet_api','staking-with-ext-wallet']
        },
        'wallet/metamask','wallet/arkane', 'wallet/math-resource',
             'wallet/trustwallet', 'wallet/ezdefi', 'wallet/infinitywallet'],
      },
    
    ],
    }, 
    
    {
      type: 'category',
      label: 'Beacon Chain',
     // collapsible: true,
      collapsed: true,
      items: ['learn/beaconIntro',
                {
                  type:'category',
                  label: 'Learn',
                  collapsed: true,
                  items:[ 'beaconchain/learn/architecture', 'beaconchain/learn/accounts', 'beaconchain/learn/assets',
                  'beaconchain/learn/transactions', 'beaconchain/learn/genesis', 'beaconchain/learn/signature',
                  {
                      type: 'category',
                      label: 'Encoding',
                      collapsed: true,
                      items: [ 'encoding', 'beaconchain/learn/encoding/encoding',
                      'beaconchain/learn/encoding/amino-example']
                  },
                  ]
                },
                {
                  type:'category',
                  label:'Develop',
                  items: [
                    {
                    type:'category',
                    label:'Beacon Chain Fullnode',
                    items:['beaconchain/develop/node/install', 'beaconchain/develop/node/join-mainnet',
                            'beaconchain/develop/node/join-testnet', 'beaconchain/develop/node/synctypes',
                          'beaconchain/develop/node/extra-info', 'beaconchain/develop/node/nodetypes',
                        'beaconchain/develop/node/upgrade', 'beaconchain/develop/node/localnetwork',
                      'beaconchain/develop/node/fullnodeissue', 'beaconchain/develop/api-reference/dex-api/staking',
                      'beaconchain/develop/node/snapshot'
                    ]
                  }, 
                  {type:'doc', id: 'beaconchain/develop/api-reference/cli', label:'Beacon Chain Client'},
                  {type:'doc', id: 'beaconchain/light-client', label:'Light Client'},
                  {type:'doc', id: 'beaconchain/develop/api-reference/api-server', label:'Simple API Server'},
                  {type:'doc', id: 'beaconchain/develop/bcsdk', label:'Beacon Chain SDK'},
                  {type:'doc', id: 'beaconchain/develop/testnetandexplorer', label:'Beacon Chain Testnet & SDK'},
                  {
                    type: 'category',
                    label:'Beacon Chain API Reference',
                    items:[
                      {type:'doc', id:'beaconchain/develop/api-reference/dex-api/paths', label: 'Accelerated Node HTTP API Mainnet - Paths and Models'},
                      {type:'doc', id:'beaconchain/develop/api-reference/dex-api/block-service', label: 'New Accelerated Node HTTP API Mainnet'},
                      {type:'link', href:'https://docs.binance.org/api-swagger/index.html', label: 'Accelerated Node HTTP API Swagger'},
                      {type:'doc', id:'beaconchain/develop/api-reference/dex-api/paths-testnet', label: 'Accelerated Node HTTP API Testnet- Paths and Models'},
                      {type:'doc', id:'beaconchain/develop/api-reference/dex-api/ws-connection', label: 'WebSockets - Connecting'},
                      {type:'doc', id:'beaconchain/develop/api-reference/dex-api/ws-streams', label: 'WebSockets - Streams'},
                      {type:'doc', id:'beaconchain/develop/api-reference/node-rpc', label: 'Node RPC - Paths and Models'},
                      {type:'link', href:'https://docs.binance.org/rpc-swagger/index.html', label: 'Node RPC Swagger'},
                      {type:'doc', id:'beaconchain/changelog', label:'CHANGELOG'}

                    ]
                  }
                  ]
                },
                {
                  type: 'category',
                  label:'Wallet',
                  items:['beaconchain/wallets',
                    {
                      type: 'category',
                      label:'Tutorials',
                      items:[
                      {type:'doc', id:'beaconchain/wallet/tutorial/how-to-create-a-wallet-on-trustwallet', label:'Trust Wallet Guide'},
                      {type:'doc', id:'beaconchain/wallet/tutorial/ledger-nano-s-usage-guide', label:'Ledger Wallet Guide'},
                      {type:'doc', id:'beaconchain/wallet/tutorial/trezor-model-t-user-guide', label:'Trezor Wallet Guide'},
                      {type:'doc', id:'beaconchain/wallet/tutorial/bep8', label:'How to manage BEP8 token with Web Wallet'},
                    ]
                    }
                  ]
                }
       ],
    },
    {
      type: 'category',
      collapsed: true,
      label: 'Future Developments',
      items:[
                {
                  type: 'category',
                  collapsed: true,
                  label: '2022 Development Outlook',
                  items:['dev-outlook-2022', 'dev-outlook/scaling', 'dev-outlook/user-exp',
                             'dev-outlook/sharding-and-multichain', 'dev-outlook/community'],
                }
      ],
    },
    {
      type: 'category',
      //collapsible: true,
      collapsed: true,
      label: 'FAQs',
      items: [      
        {
          type: 'category',
          collapsed: true,
          label: 'BNB Smart Chain FAQs',
          items: ['BSC-FAQs-general', 'BSC-FAQs-tokens', 
                  'BSC-FAQs-validator', 'BSC-FAQs-delegator', 
                  'parameters', 'cross',  'faq'],
        },
        {
          type: 'category',
          collapsed: true,
          label: 'Beacon Chain FAQs',
          items: ['beaconchain/faq/faq'],
        }, 
     ],

    },
    
    {type: 'doc',   id: 'contribute',   label: 'Contribute to BSC'},
    {type: 'doc',   id: 'more-help',   label: 'More Help'},
  ],
   
};

module.exports = sidebars;
