/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}, ],

  // But you can create a sidebar manually


  faqSideBar:[{type: 'doc',   id: 'cat-FAQs',   label: 'FAQs'}],
  
  bcSidebar:[    
    {
    type: 'category',
    label: 'Binance Chain',
   // collapsible: true,
    collapsed: true,
    items: ['bcdevelop'],//'develop','Learn','Validate','Integrate','Wallet', 'FAQs'],
     /* {
        type: 'category',
        collapsible: true,
        collapsed: false,
        label: 'Develop',
        items: ['develop'], //add the names of the docs as per the list to create
      },
      'Learn','Validate','Integrate','Wallet', 'FAQs'],*/
      },
     ],

  bscSideBar: [
    {
      type: 'category',
      collapsible: true,
      collapsed: true,
      label: 'Binance Smart Chain',
      items: [
        {type: 'category', collapsed:true,  label: 'About',   items: ['learn/intro', 'learn/terminology']},
          {
          type: 'category',
          //collapsible: true,
          collapsed: true,
          label: 'Learn',
          items: ['learn/consensus', 'learn/genesis',
                    {type: 'category',
                    //collapsible: true,
                    collapsed: true,
                    label: 'BC and BSC Cross-Chain Mechanism',
                    items: ['learn/cross-chain', 'learn/system-contract',
                            'learn/cross-chain-transfer','learn/bsc-relayer', 'learn/incentives',
                            'learn/oracle-module','learn/oracle-relayer']},
                            'learn/bsc-gov-workflow','learn/bsc-gov','learn/ecosystem',
                  'learn/cross-chain-app-list']
          },

        {type: 'category',
        //collapsible: true,
        collapsed: true,
        label: 'Developing',
        items: ['BSCmainnet', 'BSCtestnet', 'BSCexplorers',
                {
                  type: 'category',
                  //collapsible: true,
                  collapsed: true,
                  label: 'Deploy',
                  items: ['remix', 'truffle', 'hardhat','local', 'verify']
                },
                
                {
                  type: 'category',
                  //collapsible: true,
                  collapsed: true,
                  label: 'BEP20 Contracts',
                  items: ['proxy', 'verify-proxy']
                },
                'ERC721',
                {
                  type: 'category',
                  //collapsible: true,
                  collapsed: true,
                  label: 'BEP20 Tokens',
                  items: ['BEP20', 'issue-BEP20',
                            {
                              type: 'category',
                              //collapsible: true,
                              collapsed: true,
                              label: 'Bind Tokens',
                              items: ['tokens-cross-chain', 'bind-tokens', 'mirror', 
                              'circulation-model', 'sync' ]
                            },
                            'cross-chain-transfer'
                         ]
                }, 'bsc-relayer', 'rpc', 'cross-chain-tech',
                {
                  type: 'category',
                  //collapsible: true,
                  collapsed: true,
                  label: 'Oracles',
                  items: ['band',  'link']
                },
       ]},  
       
       {
        type: 'category',
        //collapsible: true,
        collapsed: true,
        label: 'Validator',
        items: ['validator/overview', 'validator/requirements','validator/fullnode', 
                {
                  type: 'category',
                  //collapsible: true,
                  collapsed: true,
                  label: 'Running as Validator on BSC',
                  items:['validator/guideline-mainnet', 'validator/guideline-testnet',
                   'validator/testnet', 'validator/snapshot', ]
                },
                'validator/security', 'validator/best-practice', 
                {
                  type: 'category',
                  collapsed: true,
                  label: 'Penalty for Bad Behaving Validators',
                  items:['validator/Penalty-overview', 'validator/send-slash-evidence', 
                         'validator/scenarios-slash', 'validator/slash-fee', 'validator/unjail',
                         'validator/monitor-and-query-slash'
                  ]
                }, 
                'validator/upgrade-fullnode','validator/node-maintenance',
                'validator/commonproblems', 'validator/troubleshoot'], 
       },

      {type: 'doc',   id: 'Integrate',   label: 'Integrate'},

      {
        type: 'category',
        //collapsible: true,
        collapsed: true,
        label: 'Wallet',
        items: ['Wallet', 'create-wallet', 'wallet/arkane', 'wallet/math-resource',
                 'wallet/trustwallet', 'wallet/ezdefi', 'wallet/infinitywallet'],
      },
    
    ],
    }, 
    
    {
      type: 'category',
      //collapsible: true,
      collapsed: true,
      label: 'Staking',
      items: ['stake/Staking', 'stake/cli-commands']
    },
    /*{type:'doc', id:'Staking', label:'Staking on BSC'},*/
    {type: 'doc',   id: 'del-guide',   label: 'Delegator Guide'},

    {
      type: 'category',
      //collapsible: true,
      collapsed: true,
      label: 'Binance Extension Wallet',
      items: ['binance','manual', 'add-account', 'wallet_api','staking-with-ext-wallet']
    },

    {
      type: 'category',
      //collapsible: true,
      collapsed: true,
      label: 'FAQs',
      items: [ 
        /*{
          type: 'category',
          //collapsible: true,
          collapsed: true,
          label: 'BC FAQs',
          items: ['BC-FAQs'], //add the names of the docs as per the list to create
        },*/
      {
        type: 'category',
        //collapsible: true,
        collapsed: true,
        label: 'BSC FAQs',
        items: ['BSC-FAQs-general', 'BSC-FAQs-tokens', 
                'BSC-FAQs-validator', 'BSC-FAQs-delegator', 
                'parameters', 'cross',  'faq'],
      }, 
      
     ],
    },

    {type: 'doc',   id: 'contribute',   label: 'Contribute to BSC'},
    {type: 'doc',   id: 'more-help',   label: 'More Help'},
  ],
   
};

module.exports = sidebars;
