{
 "title": "Storage Provider Template for opensource",
 "time": { "from": "now-d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "site",
    "label": "site",
    "query": {
     "query": "label_values(prometheus_replica)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{prometheus_replica=\"$site\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alerting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GRPC - Server Handled Total (grpc_code != \"OK\") (>10/min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(changes(grpc_server_handled_total{prometheus_replica=\"$site\",namespace=~\"gf-.*-sp.*\", grpc_code!=\"OK\"}[1m]))by(grpc_method,namespace)",
     "legendFormat": "{{namespace}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "GRPC - Client Handled Total (grpc_code != \"OK\") (>10/min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(changes(grpc_server_handled_total{prometheus_replica=\"$site\", namespace=~\"gf-.*-sp.*\", grpc_code!=\"OK\"}[1m]))by(grpc_method, namespace)",
     "legendFormat": "{{namespace}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "HTTP - request time (>10s) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(changes(http_request_duration_seconds_bucket{prometheus_replica=\"$site\", namespace=~\"gf-.*-sp.*\", le=\"+Inf\"}[1m]))by(namespace, handler_name) - sum(changes(http_request_duration_seconds_bucket{prometheus_replica=\"$site\", namespace=~\"gf-.*-sp.*\", le=\"10\"}[1m]))by(namespace, handler_name)",
     "legendFormat": "{{namespace}}/{{handler_name}}"
    }
   ]
  },
  {
   "title": "GRPC Client handling seconds (>5s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(changes(grpc_client_handling_seconds_bucket{prometheus_replica=\"$site\", namespace=~\"gf-.*-sp.*\", grpc_service=~\"service.uploader.types.UploaderService|service.tasknode.types.TaskNodeService\", grpc_method=~\"PutObject|ReplicateObject\", le=\"+Inf\"}[1m]))by(namespace, grpc_service, grpc_method) - sum(changes(grpc_client_handling_seconds_bucket{prometheus_replica=\"$site\", namespace=~\"gf-.*-sp.*\",grpc_service=~\"service.uploader.types.UploaderService|service.tasknode.types.TaskNodeService\", grpc_method=~\"PutObject|ReplicateObject\", le=\"5\"}[1m]))by(namespace, grpc_service,grpc_method)",
     "legendFormat": "{{namespace}}/{{grpc_service}}/{{grpc_method}}"
    }
   ]
  },
  { "title": "Gateway - HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "HTTP - P90 request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (job, le, method, handler_name, namespace) (rate(http_request_duration_seconds_bucket{prometheus_replica=\"$site\", namespace=\"$namespace\"}[1m])))",
     "legendFormat": "{{namespace}}/{{job}}/{{method}}/{{handler_name}}"
    }
   ]
  },
  {
   "title": "HTTP - QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{prometheus_replica=\"$site\", namespace=~\"$namespace\"}[1m]))by(job,method,handler_name,namespace)",
     "legendFormat": "{{namespace}}/{{job}}/{{method}}/{{handler_name}}"
    }
   ]
  },
  {
   "title": "HTTP - Average duration per API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{prometheus_replica=\"$site\",namespace=~\"$namespace\"}[1m]))by(job, method, handler_name, namespace)/sum(rate(http_request_duration_seconds_count{prometheus_replica=\"$site\",namespace=~\"$namespace\"}[1m]))by(job, method, handler_name, namespace)",
     "legendFormat": "{{namespace}}/{{job}}/{{method}}/{{handler_name}}"
    }
   ]
  },
  {
   "title": "HTTP - Received Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(http_server_received_total_requests{prometheus_replica=\"$site\",namespace=~\"$namespace\"})by(namespace,method,handler_name)",
     "legendFormat": "{{namespace}}/{{method}}/{{handler_name}}"
    }
   ]
  },
  { "title": "GRPC Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "GRPC - P90 request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_server_handling_seconds_bucket{prometheus_replica=\"$site\",namespace=~\"$namespace\"}[1m])) by (le, grpc_service, grpc_method, namespace))",
     "legendFormat": "{{namespace}}/{{grpc_method}}/{{grpc_service}}"
    }
   ]
  },
  {
   "title": "GRPC - QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handling_seconds_count{prometheus_replica=\"$site\",namespace=~\"$namespace\"}[1m]))by(grpc_method,grpc_service,namespace)",
     "legendFormat": "{{namespace}}/{{grpc_method}}{{grpc_service}}"
    }
   ]
  },
  {
   "title": "HTTP - Average duration per API ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handling_seconds_sum{prometheus_replica=\"$site\",namespace=~\"$namespace\"}[1m]))by(grpc_method, grpc_service, namespace)/sum(rate(grpc_server_handling_seconds_count{prometheus_replica=\"$site\",namespace=~\"$namespace\"}[1m]))by(grpc_method, grpc_service, namespace)",
     "legendFormat": "{{namespace}}/{{grpc_method}}/{{grpc_service}}"
    }
   ]
  },
  {
   "title": "GRPC - Total Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(grpc_server_handled_total{prometheus_replica=\"$site\", namespace=~\"$namespace\"})by(namespace,grpc_method,grpc_service)",
     "legendFormat": "{{namespace}}/{{grpc_method}}/{{grpc_service}}"
    }
   ]
  },
  { "title": "GRPC Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "GRPC - P90 request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_client_handling_seconds_bucket{prometheus_replica=\"$site\",namespace=~\"$namespace\"}[1m])) by (le, grpc_service, grpc_method,namespace))",
     "legendFormat": "{{namespace}}/{{grpc_method}}/{{grpc_service}}"
    }
   ]
  },
  {
   "title": "GRPC - QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_client_handling_seconds_count{prometheus_replica=\"$site\",namespace=~\"$namespace\"}[1m]))by(grpc_method,grpc_service,namespace)",
     "legendFormat": "{{namespace}}/{{grpc_method}}{{grpc_service}}"
    }
   ]
  },
  {
   "title": "HTTP - Average duration per API ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_client_handling_seconds_sum{prometheus_replica=\"$site\",namespace=~\"$namespace\"}[1m]))by(grpc_method, grpc_service,namespace)/sum(rate(grpc_client_handling_seconds_count{prometheus_replica=\"$site\",namespace=~\"$namespace\"}[1m]))by(grpc_method, grpc_service,namespace)",
     "legendFormat": "{{namespace}}/{{grpc_method}}/{{grpc_service}}"
    }
   ]
  },
  {
   "title": "GRPC - Total Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(grpc_client_handled_total{prometheus_replica=\"$site\",namespace=~\"$namespace\"})by(namespace,grpc_method,grpc_service)",
     "legendFormat": "{{namespace}}/{{grpc_method}}/{{grpc_service}}"
    }
   ]
  }
 ]
}